### PR TITLE
add buttons, add index.css

### PR DESCRIPTION
**Pull request by shannonscotta**
Implement design
- [x]  Layout and css
- [x] Accessibility for mobile
- [x] Finalize design

### CODE REVIEW

**Comment by gorhack** [comment]
@shannonscotta @mojo9492 @bry-git take a look at my changes b3a314c. Should be decently responsive to a mobile layout. Still needs some final touches, but hopefully this gets you guys on the right track. Let me know if you have any questions about any changes or if you need additional help to get it to the right [design](https://www.figma.com/file/IXUa5y6afNAo8DsDfIKrdx/Ranger-ranger-ranger-ranger?node-id=171%3A0).

**Review by mojo9492 — APPROVED** [review]
When in doubt, flex wrap all... Got it.

**Comment by gorhack** [comment]
@mojo9492 it's not "final" yet. Still could use some styling work that I didn't want to mess with. I am fine with merging it in, but could also see some of you guys taking some time to make it right. I just tried to get you guys on the right path.

**Comment by mojo9492** [comment]
I appreciate and will work on it this week

**Pull request merged**
